# SPDX-FileCopyrightText: 2022 Calvin Walton
#
# SPDX-License-Identifier: CC0-1.0

name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build HTML
      uses: ammaraskar/sphinx-action@0.4
      with:
        build-command: "sphinx-build -b html . ../build/html"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: build/html
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
