# SPDX-FileCopyrightText: 2022 Calvin Walton
#
# SPDX-License-Identifier: CC0-1.0

name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8", "3.10" ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: requirements-dev.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Check formatting with black
      run: black --check --target-version py38 .
    - name: Check types with mypy
      run: mypy
    - name: Test with pytest
      run: pytest --junitxml=junit/test-results.xml
